server:
  port: 8082

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: AI-service
              uri: http://localhost:8083
              predicates:
                - Path=/chat-service/**
          globalcors:
            corsConfigurations:
              '[/**]':
                allowed-origins:
                  -  "*"
                allowed-methods:
                  - GET
                  - POST
                  - OPTIONS
                allowed-headers:
                  - "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  healthcheck:
    enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
